### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xzakier** [nickheyer/DiscoClip#2]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 113, in on_message
    await on_valid_url(message)
  File "bot.py", line 57,...

also not responding to any like only for the one that you give in the ode page i think you should update the parameters for identifying because tiktok changed them from https://www.tiktok.com/t/video id  to https://www.tiktok.com/@user/video/video id

**Comment by nickheyer** [comment]
This is being addressed in the next release. Can you provide an example tiktok share url?

**Comment by xzakier** [comment]
https://www.tiktok.com/@kevintheprogrammer/video/7137664818365943046 (from wep tiktok)

for mobile it's the same but with some additions

**Comment by nickheyer** [comment]
This was a good catch, consider it being added. I need to do further research into various URL formats for both platforms as this did not come up in my testing.

**Comment by nickheyer** [comment]
Also @xzakier, when pasting the bug report, please paste the contents of the .txt file that was attached below that message. Thanks!

(What you provided was a shortened version)
![image](https://user-images.githubusercontent.com/60236014/220177263-704c3f65-17e2-4198-af5c-ddacf24dab73.png)
